### ISSUE TITLE
Change license to LGPLv3

### ISSUE THREAD

**Issue by ExE-Boss** [TanninOne/usvfs#5]
I would like to relicense the User Space Virtual File System to be under the [GNU Lesser General Public License version 3](https://www.gnu.org/licenses/lgpl-3.0.html). This will make it possible for USVFS to be used by programs that are not GPL licensed.

This doesn’t affect Mod Organizer, because Mod Organizer is licensed under the GPLv3, because it uses USVFS, which itself is GPLv3 currently.

@TanninOne, @LePresidente if you agree with moving to this more free license, please write a comment confirming this.

- [ ] @TanninOne
- [ ] @LePresidente

**Comment by LePresidente** [comment]
It is completely up to @TanninOne, It is his project

**Comment by TanninOne** [comment]
Sorry, I don't agree with a change to LGPL, the reason being that I don't like the thought that a commercial closed-source software could then use it for free.

However, I would agree to a change to the current license to add an exception for open source projects, similar to this: https://github.com/billziss-gh/winfsp/blob/master/License.txt
So basically: "If your project has a license that is considered a free software license (which would include Apache, BSD, ISC, MPL, ...) you can use usvfs without any further steps. If you want to use usvfs in a closed-source project, please contact me so we can work something out. All modifications to usvfs must still be released under the GPL"

If this is agreeable to you I'd like to change the license in this official repo and then you can fork from that if you like.

Also, this case shows that it would make sense to set up a contributors agreement. No offense to LePresidente, you did great work on the MO project, but I don't like the thought of having to ask everyone who has ever contributed two changes for permission when changing/updating/adding a license.
So the idea would be: "You send a small pull request? Please agree to waive all your rights that arise from your copyright to that code. You contribute some serious code? Please send me your real world info so I can make you a contributor and contact you if need be. You agree that if I can't reach you after seriously trying on all communication channels available for 4 weeks you implicitly waive your rights bla bla".
Anyone know a free lawyer to set something like that up? ;)

**Comment by LePresidente** [comment]
@TanninOne  no offence taken, to be honest don't like the "Contributor" tag in github to be given solely on any commit done to a repo. Confuses things

**Comment by TanninOne** [comment]
Yeah, but I guess legally it's like this: You own the code you contributed, even if it's just two lines. I can't change the license on your code without your permission. Thus I either need your permission or replace your contribution, unless you give me general permission for stuff like that.

**Comment by ExE-Boss** [comment]
I believe that all that is necessary is just the open source project exemption clause as specified by @TanninOne in [comment 3](#issuecomment-316679311).

Mod Organizer is unaffected by this change because it is already open source and GPL licensed because it uses GPL licensed libraries (ex. usvfs and LOOT).

**Comment by TanninOne** [comment]
sorry for the long delay. I've now added additional permissions to the license that should allow you to use usvfs with any FOSS licensed software.
